###

POST http://localhost:5001/v1/clients/register HTTP/1.1
content-type: application/json

{
  "item":{
    "username":"mario",
    "password":"gino",
    "preferredCategories":["Bici"],
    "payment":"PayPal",
    "fidelityPoints":32,
    "favourites":["61b1bfed920b3b3b7167f9ab"],
    "notifications":["61b1bfed920b3b3b7167f9ab"]
  }
}

###

POST http://localhost:5001/v1/clients/login HTTP/1.1
content-type: application/json

{
  "item":{
    "username":"mario",
    "password":"gino"

  }
}
###

GET http://localhost:5001/v1/clients/lookup HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlvIiwiaWF0IjoxNjM5NjUxMTk0fQ.704IeblqIA6FgF2ciSw-ITth_nIb-gG0LJATPn16WQU
content-type: application/json

{
  "item":{
    "username":"mario"

  }
}
###

GET http://localhost:5001/v1/clients/lookup HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhb2xvIiwicm9sZSI6ImZ1bnppb25hcmlvIiwiaWF0IjoxNjM5NjUyNjUxfQ.GBsxbf0XcD-t3vaqmuWBEQwhhbERS-K6qvI1mqb-58Q
content-type: application/json

{
  "item":{
    "username":"mario"

  }
}
