POST http://localhost:5000/v1/inventories/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdpbm8iLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY0MTY1NzkyOSwiZXhwIjoxNjQxNjU4ODI5fQ.U6_XDg3A8IOm4mbG-P_SsQ5Pgg41-j94FxF5F-36nkw
content-type: application/json

{
  "item":{
    "available":true,
    "price":{
      "weekend":25,
      "weekday":50,
      "points":200
    },
    "condition":"Buona",
    "category":"Bici",
    "title":"Mountain bike",
    "description":"Bellissima bici"
  }
}

###
GET http://localhost:5000/v1/inventories/findOne HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdpbm8iLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTYzOTY1MzAxMn0.YwqS7LOOnbsOTqhXMn_526-n0N5HgSIzwBxFsoxzcMA
content-type: application/json

{
  "item":{
    "title":"Mountain bike"
  }
}

###
GET http://localhost:5000/v1/inventories/findOne HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdpbm8iLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTYzOTY1MzAxMn0.YwqS7LOOnbsOTqhXMn_526-n0N5HgSIzwBxFsoxzcMA
content-type: application/json

{
  "item":{
    "category":"Bici"
  }
}
###
GET http://localhost:5000/v1/inventories/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdpbm8iLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTYzOTY1MzAxMn0.YwqS7LOOnbsOTqhXMn_526-n0N5HgSIzwBxFsoxzcMA
content-type: application/json

{
  "item":{
    "title":"Mountain bike",
    "available":false
  }
}

###
GET http://localhost:5000/v1/inventories/category HTTP/1.1
content-type: application/json

{
  "item":{
    "category":"Bici"
  }
}

###
GET http://localhost:5000/v1/inventories/product HTTP/1.1
content-type: application/json

{
  "item":{
    "title":"Mountain bike"
  }
}